[pyprland]
plugins = [
  "scratchpads",
  "wallpapers",
  "monitors",
  "expose"
]

[wallpapers]
path = "~/megasync/main/Pictures/Wallpapers_1/" # path to the folder with background images
extentions = ["png", "jpg", "jpeg", "webp"]
unique = true # set a different wallpaper for each screen
interval = 15
command = "swww img --transition-type any \"[file]\""
clear_command = "swww clear"

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "85% 75%"
max_size = "2400px 100%"
margin = 50

[scratchpads.volume]
animation = "fromTop"
command = "pwvucontrol"
class = "com.saivert.pwvucontrol"
size = "33% 50%"
unfocus = "hide"
lazy = true

[scratchpads.telegram]
animation = "fromBottom"
command = "telegram-desktop"
class = "org.telegram.desktop"
size = "35% 90%"
multi = true

[scratchpads.obsidian]
animation = "fromBottom"
command = "obsidian"
class = "obsidian"
size = "50% 80%"
lazy = true


[scratchpads.mega]
animation = "fromTop"
command = "megasync"
class = "nz.co.mega"
size = "20% 50%"
unfocus = "hide"



