[pyprland]
plugins = [
  "scratchpads",
  "wallpapers",
  "expose",
  "shortcuts_menu"
]

[expose]
include_special = true

[wallpapers]
path = "~/.config/wallpapers_ln" # path to the folder with background images
extentions = ["png", "jpg", "jpeg", "webp"]
unique = true # set a different wallpaper for each screen
interval = 15
command = 'swww img --transition-type any "[file]"'
clear_command = "swww clear"

[scratchpads.term]
animation = "fromTop"
# command = "kitty --class kitty-dropterm"
# class = "kitty-dropterm"
command = "ghostty --class=com.mitchellh.ghostty.dropdown"
class = "com.mitchellh.ghostty.dropdown"
size = "85% 75%"
max_size = "2400px 100%"
margin = 50
allow_special_workspaces = true
multi = false

[scratchpads.volume]
animation = "fromTop"
command = "pwvucontrol"
class = "com.saivert.pwvucontrol"
size = "33% 50%"
unfocus = "hide"
lazy = true
allow_special_workspaces = true

[shortcuts_menu.entries]
"chromium" = "chromium"

# [scratchpads.telegram]
# animation = "fromBottom"
# command = "telegram-desktop"
# class = "org.telegram.desktop"
# multi = false
# position = "5% 5%"
# size = "35% 90%"
# allow_special_workspaces = true
#
# [scratchpads.obsidian]
# animation = "fromBottom"
# command = "obsidian"
# class = "obsidian"
# multi = false
# size = "50% 80%"
# lazy = true
