hl.on("hyprland.start", function()
  hl.exec_cmd("uwsm app -s b -- clipse -listen")
  hl.dispatch(hl.dsp.exec_cmd("uwsm app -s a -- zen-beta --name zen-beta", { workspace = "1 silent" }))
  hl.dispatch(hl.dsp.exec_cmd("uwsm app -s a chromium",                    { workspace = "7 silent" }))
  hl.dispatch(hl.dsp.exec_cmd("uwsm app -s a kitty",                       { workspace = "2 silent" }))
  hl.dispatch(hl.dsp.exec_cmd("uwsm app -s a -- AyuGram",     { workspace = "4 silent" }))
  hl.dispatch(hl.dsp.exec_cmd("uwsm app -s a obsidian",       { workspace = "11 silent" }))
  hl.dispatch(hl.dsp.exec_cmd("uwsm app -s a cryptomator",    { workspace = "special:scratch_hidden silent" }))
  hl.dispatch(hl.dsp.exec_cmd("uwsm app -s a filen-desktop", { workspace = "special:scratch_hidden silent" }))
end)
