services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
      LANGUAGE: English
      DISK_SIZE: "64G"
      RAM_SIZE: "16G"
      CPU_CORES: "8"
      USERNAME: "VM"
      ARGUMENTS: "-device ich9-intel-hda -device hda-output -audio alsa"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - /home/mykolas/win:/storage
