# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
      kernelModules = ["amdgpu"];
    };
    kernelModules = ["kvm-amd" "ecryptfs"];
    extraModulePackages = [];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/f9741ad7-b731-4703-81a0-3828210fa7cb";
      fsType = "ext4";
    };
  };

  boot.initrd.luks.devices."luks-dfdd5e0b-19b1-4965-80db-24a04a65fb77".device = "/dev/disk/by-uuid/dfdd5e0b-19b1-4965-80db-24a04a65fb77";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D4C1-E126";
    fsType = "vfat";
  };

  swapDevices = [
    # {device = "/dev/disk/by-uuid/75c5aebf-caaa-46c5-960b-a2c2ac343b74";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware = {
    enableAllFirmware = true;
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    opengl = {
      driSupport = true; # This is already enabled by default
      driSupport32Bit = true; # For 32 bit applications
      extraPackages = with pkgs; [
        rocmPackages.clr.icd
      ];
      extraPackages32 = with pkgs; [
      ];
    };

    bluetooth = {
      enable = true;
      settings = {General = {Enable = "Source,Sink,Media,Socket";};};
    };
    ledger.enable = true; # udev rules for ledger
  };
}
